# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataplane.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dataplane.proto',
  package='dataplane',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x64\x61taplane.proto\x12\tdataplane\"D\n\x05\x44PMsg\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.dataplane.Type\x12\r\n\x05\x64p_id\x18\x02 \x01(\t\x12\r\n\x05op_id\x18\x03 \x01(\t*\x1a\n\x04Type\x12\x08\n\x04PUSH\x10\x00\x12\x08\n\x04PULL\x10\x01\x62\x06proto3')
)

_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='dataplane.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PUSH', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PULL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=100,
  serialized_end=126,
)
_sym_db.RegisterEnumDescriptor(_TYPE)

Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
PUSH = 0
PULL = 1



_DPMSG = _descriptor.Descriptor(
  name='DPMsg',
  full_name='dataplane.DPMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='dataplane.DPMsg.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dp_id', full_name='dataplane.DPMsg.dp_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_id', full_name='dataplane.DPMsg.op_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=98,
)

_DPMSG.fields_by_name['type'].enum_type = _TYPE
DESCRIPTOR.message_types_by_name['DPMsg'] = _DPMSG
DESCRIPTOR.enum_types_by_name['Type'] = _TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DPMsg = _reflection.GeneratedProtocolMessageType('DPMsg', (_message.Message,), dict(
  DESCRIPTOR = _DPMSG,
  __module__ = 'dataplane_pb2'
  # @@protoc_insertion_point(class_scope:dataplane.DPMsg)
  ))
_sym_db.RegisterMessage(DPMsg)


# @@protoc_insertion_point(module_scope)
